### ISSUE TITLE
bug: server.js not able to connect to db4free mysql database

### ISSUE THREAD

**Issue by JeanCarlosChavarriaHughes** [JeanCarlosChavarriaHughes/sopa#2]
El servidor de node, server.js no logra conectarse a la base de datos almacenada en db4free.net

```
var mysql       = require('mysql')  // npm install mysql
  , q           = require('q')      // npm install q
  , util        = require('util')
  , queue       = []
  , clientOpts  = {
        host        : 'sopa',
        user        : 'root_imagine',
        port        : '3306',
        password    : 'sopaimagine',
        database    : 'db4free.net'
    };

// If you have a correct host in clientOpts but a wrong user/name/db, you'll receive an error immediately.


var pool    = mysql.createPool(clientOpts);

pool.on('connection', function(connection) {
    util.log('Connected to MySql db');
});

pool.on('error', function(err) {
    util.log('Oh shit.');
    throw err;
});

exports.query = query;
function query(query, values) {
    var link;

    return q.nfcall(pool.getConnection.bind(pool))
    .then(function(connection) {
        link = connection; // scope
        return q.nfcall(link.query.bind(link), query, values);
    })
    .timeout(15000, 'Big fat timeout') // Adding short timeout because the default is a few minutes
    .then(function(rows) {
        link.release();
        return rows;
    })
    .fail(function (err) {
        util.log(err);
        throw err;
    });
}


// Test the connection
this.query('SELECT 1').then(function(rows) {
    util.log(rows);
}).done();

```

Cuando ejecuto la aplicacion, el servidor inicia el listen bien, pero después de un par de segundos falla y no logra conectarse al a DB. Tiene un ETIMEDOUT 

Server has started sucessfully in port: 8181

26 Feb 09:17:51 - Error: connect ETIMEDOUT

/home/black/local/sopa/node_modules/q/q.js:155
                throw e;
                      ^
Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/home/black/local/sopa/node_modules/mysql/lib/Connection.js:419:13)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:92:17)
    at Socket._onTimeout (net.js:326:8)
    at Timer.unrefTimeout [as ontimeout] (timers.js:418:13)
    --------------------
    at Protocol._enqueue (/home/black/local/sopa/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/black/local/sopa/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/black/local/sopa/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/black/local/sopa/node_modules/mysql/lib/Pool.js:48:16)
    at Promise.apply (/home/black/local/sopa/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/home/black/local/sopa/node_modules/q/q.js:788:41)
    at /home/black/local/sopa/node_modules/q/q.js:1391:14
    at runSingle (/home/black/local/sopa/node_modules/q/q.js:137:13)
    at flush (/home/black/local/sopa/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)

npm ERR! sopa@1.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the sopa@1.0.0 start script.
npm ERR! This is most likely a problem with the sopa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sopa
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.13-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/black/local/sopa
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/black/local/sopa/npm-debug.log
npm ERR! not ok code 0

**Comment by JeanCarlosChavarriaHughes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(30) Desarrollo Restaurante C,V](https://trello.com/c/noUNYvbP/24-30-desarrollo-restaurante-c-v)

**Comment by JeanCarlosChavarriaHughes** [comment]
@laco27  Alguna manera de conectarse à la base de datos remota desde nodejs?

Las pruebas del codigo de nodejs funcionan bien cuando la base es local, (deberia funcionar cuando son remotas tambien pero no funciona con db4free).

Alguno otro host remoto para probar.

**Comment by JeanCarlosChavarriaHughes** [comment]
Solved by using Cloud SQL. 
db4free did not work for our needs.
